name: ChromeOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ChromeOS:
    name: ChromeOS
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update && sudo apt -y upgrade && sudo apt -y install wget pv tar unzip cgpt lzip
      - name: Download ChromeOS
        run: |
          cd $HOME
          mkdir Project
          cd /home/runner/Project
          wget "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      - name: Download Brunch
        run: |
          cd /home/runner/Project
          wget "https://github.com/sebanc/brunch/releases/download/r94-stable-20211121/brunch_r94_stable_20211127.tar.gz"
      - name: Extract ChromeOS and Brunch
        run: |
          cd /home/runner/Project
          echo "#!/bin/sh
          echo "Installing Dependencies"
          sudo apt update && sudo apt -y install wget pv tar grub-customizer unzip cgpt lzip 
          read -p "In which folder do you want to install ChromeOS eg. "/home/user/"" location
          read -p "What size will you give ChromeOS eg. "20G" for 20 GiB" size
          read -p "You are sure? [y/n]" yn
          case $yn in
              [Yy]* ) echo "Ok, Proceeding installation on $location";
                      chmod +x chromeos-install.sh;
                      sudo bash chromeos-install.sh -src chromeos_recovery.bin -dst $location -s $size;
                      read -p "Do you want to add boot options to ChromeOS? [y/n]" boot;
                      case $boot in;
                          [Yy]* ) echo "Copy the above grub menu entry in grub customizer";
                                  sudo grub-customizer;
                                  break;;
                          [Nn]* ) exit;;
                          * ) echo "Please answer yes or no.";;
                      break;;
              [Nn]* ) exit;;
              * ) echo "Please answer yes or no.";;" > ChromeOS-Install.sh
          chmod +x ChromeOS-Install.sh
          unzip "chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
          tar zxvf "brunch_r94_stable_20211127.tar.gz"
      - name: Delete Temporary File
        run: |
          cd /home/runner/Project
          rm "chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
          rm "brunch_r94_stable_20211127.tar.gz"
          mv *.bin chromeos_recovery.bin
      - name: Compress File
        run: |
          cd /home/runner/Project
          tar vc /home/runner/Project/* | xz -ve > ChromeOS.tar.xz
      - name: Upload ChromeOS
        uses: actions/upload-artifact@v2
        with:
          name: ChromeOS.tar.xz
          path: '/home/runner/Project/ChromeOS.tar.xz'
