name: ChromeOS
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      chromeos:
        description: "ChromeOS Download link"
        required: true
        default: "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      brunch:
        description: "Brunch Download link"
        required: true
        default: "https://github.com/sebanc/brunch/releases/download/r94-stable-20211121/brunch_r94_stable_20211127.tar.gz"

jobs:
  ChromeOS:
    name: ChromeOS
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install wget pv tar unzip cgpt lzip
      - name: Download ChromeOS
        run: |
          cd $HOME
          mkdir Project
          cd /home/runner/Project
          wget "${{ github.event.inputs.chromeos }}"
      - name: Download Brunch
        run: |
          cd /home/runner/Project
          wget "${{ github.event.inputs.brunch }}"
      - name: Download Script
        run: |
          cd /home/runner/Project
          wget "https://github.com/FarelRA/ChromeOS/blob/main/multi-install.sh"
      - name: Extract ChromeOS and Brunch
        run: |
          cd /home/runner/Project
          unzip *recovery_stable-channel_mp-v2.bin.zip
          tar zxvf *.tar.gz
          mv *.bin chromeos_recovery.bin
          chmod +x multi-install.sh
      - name: Delete Temporary File
        run: |
          cd /home/runner/Project
          rm *recovery_stable-channel_mp-v2.bin.zip
          rm *.tar.gz
      - name: Compress File
        run: |
          cd /home/runner/Project
          tar vcf ChromeOS.tar *
          xz -ve ChromeOS.tar
      - name: Upload ChromeOS
        uses: actions/upload-artifact@v2
        with:
          name: ChromeOS.tar.xz
          path: '/home/runner/Project/ChromeOS.tar.xz'
