name: ChromeOS Image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ChromeOS-Image:
    name: ChromeOS Image
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update && sudo apt -y upgrade && sudo apt -y install wget pv tar unzip cgpt lzip
      - name: Download ChromeOS
        run: |
          cd "$HOME"
          mkdir "Project"
          cd "/home/runner/Project"
          wget "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      - name: Download Brunch
        run: |
          cd "/home/runner/Project"
          wget "https://github.com/sebanc/brunch/releases/download/r94-stable-20211121/brunch_r94_stable_20211127.tar.gz"
      - name: Extract ChromeOS and Brunch
        run: |
          cd "/home/runner/Project"
          unzip "chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
          tar zxvf "brunch_r94_stable_20211127.tar.gz"
          chmod +x "chromeos-install.sh"
      - name: Delete Temporary File
        run: |
          cd "/home/runner/Project"
          rm "chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
          rm "brunch_r94_stable_20211127.tar.gz"
          mv *.bin chromeos_recovery.bin
      - name: Make img
        run: |
          cd "/home/runner/Project"
          mkdir "/home/runner/Project/img"
          mkdir "/home/runner/Project/build-img"
          sudo bash chromeos-install.sh -src chromeos_recovery.bin -dst "/home/runner/Project/build-img/ChromeOS.img" -s 14
      - name: Compress File
        run: |
          cd "/home/runner/Project/build-img"
          sudo xz -vze *
          sudo mv "/home/runner/Project/build-img/ChromeOS.img.xz" "/home/runner/Project/img/ChromeOS-Image.xz"
      - name: Upload ChromeOS
        uses: actions/upload-artifact@v2
        with:
          name: ChromeOS-Image.xz
          path: |
            "/home/runner/Project/img/ChromeOS-Image.xz"
