name: ChromeOS Image

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      chromeos:
        description: "ChromeOS Download link"
        required: true
        default: "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      brunch:
        description: "Brunch Download link"
        required: true
        default: "https://github.com/sebanc/brunch/releases/download/r94-stable-20211121/brunch_r94_stable_20211127.tar.gz"

jobs:
  ChromeOS-Image:
    name: ChromeOS Image
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install wget pv tar unzip cgpt lzip
      - name: Download ChromeOS
        run: |
          cd $HOME
          mkdir Project
          cd /home/runner/Project
          wget "${{ github.event.inputs.chromeos }}"
      - name: Download Brunch
        run: |
          cd /home/runner/Project
          wget "${{ github.event.inputs.brunch }}"
      - name: Extract ChromeOS and Brunch
        run: |
          cd /home/runner/Project
          unzip *recovery_stable-channel_mp-v2.bin.zip
          tar zxvf *.tar.gz
          mv *.bin chromeos_recovery.bin
          chmod +x chromeos-install.sh
      - name: Delete Temporary File
        run: |
          cd "/home/runner/Project"
          rm *recovery_stable-channel_mp-v2.bin.zip
          rm *.tar.gz
      - name: Make img
        run: |
          cd "/home/runner/Project"
          mkdir "/home/runner/Project/build-img"
          sudo bash chromeos-install.sh -src chromeos_recovery.bin -dst /home/runner/Project/build-img/ChromeOS.img -s 14
      - name: Compress File
        run: |
          cd "/home/runner/Project/build-img"
          tar vcf ChromeOS-Image.tar *
          xz -ve ChromeOS-Image.tar
      - name: Check Compressed File Checksum
        run: |
          cd "/home/runner/Project/build-img"
          echo SHA-256
          sha256sum ChromeOS-Image.tar.xz
          echo "-------------------------------------------------------------------------------"
          echo MD5
          md5sum ChromeOS-Image.tar.xz
      - name: Upload ChromeOS Image
        uses: actions/upload-artifact@v2
        with:
          name: ChromeOS-Image.tar.xz
          path: '/home/runner/Project/build-img/ChromeOS-Image.tar.xz'
