name: ChromeOS
on:
  push:
  pull_request:

jobs:
  ChromeOS:
    name: ChromeOS
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install wget pv tar unzip cgpt lzip
      - name: Download ChromeOS
        run: |
          cd $HOME
          mkdir Project
          cd /home/runner/Project
          wget "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14324.62.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      - name: Download Brunch
        run: |
          cd /home/runner/Project
          wget "https://github.com/sebanc/brunch/releases/download/r97-stable-20220121/brunch_r97_stable_20220121.tar.gz"
      - name: Download Script
        run: |
          cd /home/runner/Project
          wget "https://raw.githubusercontent.com/FarelRA/ChromeOS/main/multi-install.sh"
      - name: Extract ChromeOS and Brunch
        run: |
          cd /home/runner/Project
          unzip *recovery_stable-channel_mp-v2.bin.zip
          tar zxvf *.tar.gz
          mv *.bin chromeos_recovery.bin
          chmod +x multi-install.sh
      - name: Delete Temporary File
        run: |
          cd /home/runner/Project
          rm *recovery_stable-channel_mp-v2.bin.zip
          rm *.tar.gz
      - name: Compress File
        run: |
          cd /home/runner/Project
          tar vcf ChromeOS.tar *
          xz -ve ChromeOS.tar
      - name: Check Compressed File Checksum
        run: |
          cd /home/runner/Project
          echo SHA-256
          sha256sum ChromeOS.tar.xz
          echo "---------------------------------------------------------------------------------"
          echo MD5
          md5sum ChromeOS.tar.xz
      - name: Upload ChromeOS
        uses: actions/upload-artifact@v2
        with:
          name: ChromeOS.tar.xz
          path: '/home/runner/Project/ChromeOS.tar.xz'
