name: ChromeOS

on:
  workflow_dispatch:
    inputs:
      chromeos:
        description: "ChromeOS Download link (.bin.zip)"
        required: true
        default: "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
      brunch:
        description: "Brunch Download link (.tar.gz)"
        required: true
        default: "https://github.com/sebanc/brunch/releases/download/r94-stable-20211121/brunch_r94_stable_20211127.tar.gz"

jobs:
  ChromeOS:
    name: ChromeOS
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install pv tar unzip cgpt lzip zstd aria2
      - name: Download ChromeOS
        run: |
          aria2c -x16 -s1024 "${{ github.event.inputs.chromeos }}"
      - name: Download Brunch
        run: |
          aria2c -x16 -s1024 "${{ github.event.inputs.brunch }}"
      - name: Download Install Script
        run: |
          aria2c -x16 -s1024 "https://raw.githubusercontent.com/FarelRA/ChromeOS/main/multi-install.sh"
      - name: Extract ChromeOS and Brunch Archive
        run: |
          unzip *.bin.zip
          tar zxvf *.tar.gz
          mv *.bin chromeos_recovery.bin
          chmod +x chromeos-install.sh
      - name: Delete Temporary File
        run: |
          rm *.bin.zip
          rm *.tar.gz
      - name: Compress File
        run: |
          export ZSTD_CLEVEL=19
          export ZSTD_NBTHREADS=2
          tar --create --zstd --remove-files --file ChromeOS.tar.zst *
      - name: Check Compressed File Checksum
        run: |
          echo SHA-256
          sha256sum ChromeOS.tar.zst
          echo "---------------------------------------------------------------------------------"
          echo MD5
          md5sum ChromeOS.tar.zst
      - name: Upload ChromeOS
        uses: actions/upload-artifact@v4
        with:
          name: ChromeOS
          path: ChromeOS.tar.zst
